[server]
bind_address = "0.0.0.0"

[ui]
enabled = true

[blob_store.fs]
root_dir = "/data"

[global.access_policy]
default = "allow"

[auth.identity.${push.username}]
username = "${push.username}"
password = "${push.password_hash}"

[global.scan]
url = "${scan.url}"
token = "${scan.token}"

%{ for path, registry in registries ~}
[repository."${path}"]
namespace = "${registry.name}"
scan = true

[[repository."${path}".upstream]]
url = "${registry.remote}"
%{ endfor ~}
