apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-config
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5s
  dependsOn:
    - name: security
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/clusters/local/security-config
  prune: true
  timeout: 2m
