apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: datastores
spec:
  interval: 1h
  chart:
    spec:
      chart: nats
      version: 2.14.6
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: nats-values
      valuesKey: values.yaml
