apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: main
  namespace: secrets
spec:
  provider:
    webhook:
      url: "http://secrets.cloud.test:80/{{ .remoteRef.key | replace \"%2F\" \"/\" }}"
      result:
        jsonPath: "$"
  conditions:
    - namespaces:
        - flux-system
        - certificates
        - objects
        - observability
        - backups
        - access
