apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 12h
  chart:
    spec:
      chart: external-secrets
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 1
    extraObjects:
      - apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        metadata:
          name: main
          namespace: external-secrets
          annotations:
            helm.sh/hook: post-install
        spec:
          provider:
            webhook:
              url: https://secrets.cloud.test/?key={{ `{{ .remoteRef.key }}` }}
              result:
                jsonPath: "$"
              caProvider:
                type: Secret
                name: flux-ca
                namespace: flux-system
                key: ca.crt
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: bucket-credentials
          namespace: flux-system
          annotations:
            helm.sh/hook: post-install
        spec:
          secretStoreRef:
            name: main
            kind: ClusterSecretStore
          target:
            creationPolicy: Owner
          refreshInterval: 1h0m0s
          dataFrom:
            - extract:
                key: /_/bucket-credentials
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: cloud-trust-bundle
          namespace: flux-system
          annotations:
            helm.sh/hook: post-install
        spec:
          refreshInterval: 24h
          secretStoreRef:
            name: main
            kind: ClusterSecretStore
          target:
            creationPolicy: Owner
          dataFrom:
            - extract:
                key: /_/cloud-trust-bundle
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: intermediate-ca
          namespace: cert-manager
          annotations:
            helm.sh/hook: post-install
        spec:
          refreshInterval: 24h
          secretStoreRef:
            name: main
            kind: ClusterSecretStore
          target:
            creationPolicy: Owner
            template:
              type: kubernetes.io/tls
          dataFrom:
            - extract:
                key: /cert-manager/intermediate-ca

