apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openobserve.helm-release.yaml
  - openobserve-collector.helm-release.yaml
  - kube-state-metrics.helm-release.yaml
  - metrics-server.helm-release.yaml
  - vpa.helm-release.yaml
  - openobserve-credentials.external-secret.yaml
  - openobserve-s3-credentials.external-secret.yaml
