apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openobserve-credentials
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: observability/openobserve-credentials
