apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: backups
  config:
    s3Url: http://s3.cloud.test
    s3ForcePathStyle: "true"
    region: local
  credential:
    name: velero-s3-credentials
    key: default
