apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: backups/velero-s3-credentials
