apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# every yaml in the dir must be registered here — unregistered files get pruned by flux
resources:
  - cilium.helm-release.yaml
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml=cilium-values.yaml
    options:
      disableNameSuffixHash: true
