apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/backups-config
  - default.backup-storage-location.yaml
  - talos-backup-s3-credentials.external-secret.yaml
  - talos-backup-age-public-key.external-secret.yaml
  - talos-backup.vpa.yaml
  - velero-s3-credentials.external-secret.yaml
