apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup-age-public-key
  namespace: backups
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: backups/talos-backup-age-public-key
