apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: pvcs
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces: ["*"]
    includedResources: []
    defaultVolumesToFsBackup: true
    snapshotVolumes: false
    ttl: 168h
    storageLocation: default
