apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: monitoring
  namespace: monitoring
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: objects
    - toEntities:
        - kube-apiserver
    - toEntities:
        - cluster
    # Prometheus scrapes all pods (metrics)
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "10250"   # kubelet
              protocol: TCP
            - port: "9100"    # node-exporter
              protocol: TCP
    # Fetch Grafana dashboards
    - toFQDNs:
        - matchName: grafana.com
        - matchPattern: "**.grafana.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: raw.githubusercontent.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toFQDNs:
        - matchName: smtp.cloud.test
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
