apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: security
  namespace: kubescape
spec:
  endpointSelector: {}
  egress:
    # operator -> storage, scheduler -> operator, kubescape -> storage
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kubescape
    # kubescape/operator scan & watch cluster resources
    - toEntities:
        - kube-apiserver
