apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/storage
configMapGenerator:
  - name: local-path-provisioner-values
    namespace: storage
    files:
      - values.yaml=local-path-provisioner-values.yaml
    options:
      disableNameSuffixHash: true
