apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: policies
  namespace: policies
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
        - host
        - remote-node
  ingress:
    - fromEntities:
        - kube-apiserver
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP
            - port: "443"
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: policies
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
