apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: logging
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: logging/loki-s3-credentials
