apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets-operator.helm-release.yaml
configMapGenerator:
  - name: external-secrets-values
    namespace: secrets
    files:
      - values.yaml=external-secrets-values.yaml
    options:
      disableNameSuffixHash: true
