apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-grafana-credentials
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: observability/main-grafana-credentials
