apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resource-quota.yaml
  - logging.resource-quota.yaml
  - logging.limit-range.yaml
  - openobserve.vertical-pod-autoscaler.yaml
  - o2-sync
