apiVersion: v1
kind: LimitRange
metadata:
  name: compute-defaults
  namespace: observability
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 64Mi
      defaultRequest:
        cpu: 10m
        memory: 24Mi
