apiVersion: v1
kind: ResourceQuota
metadata:
  name: logging-compute
  namespace: observability
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 10Gi
    limits.cpu: 20
    limits.memory: 16Gi
    pods: "36"
