apiVersion: source.toolkit.fluxcd.io/v1
kind: Bucket
metadata:
  name: main
  namespace: flux-system
spec:
  interval: 5m
  endpoint: s3.cloud.test
  bucketName: flux
  secretRef:
    name: bucket-credentials
  insecure: true
  provider: generic
  timeout: 60s
