apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-cilium-system-components
  namespace: kyverno
spec:
  policyRefs:
    - name: disallow-capabilities-strict
      kind: ValidatingPolicy
    - name: disallow-host-namespaces
      kind: ValidatingPolicy
    - name: disallow-host-path
      kind: ValidatingPolicy
    - name: disallow-host-ports
      kind: ValidatingPolicy
    - name: disallow-privileged
      kind: ValidatingPolicy
    - name: require-run-as-nonroot
      kind: ValidatingPolicy
    - name: restrict-seccomp-strict
      kind: ValidatingPolicy
  matchConditions:
    - name: match-cilium
      expression: "object.metadata.namespace == 'kube-system' && object.metadata.name.startsWith('cilium')"
