apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: platform-policies
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      io.cilium/app: operator
