apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-trivy-scan-jobs
  namespace: policies
spec:
  reportResult: skip
  policyRefs:
    - name: deny-shell-entrypoint
      kind: ValidatingPolicy
  matchConditions:
    - name: match-trivy-scan-jobs
      expression: "object.metadata.namespace == 'scanning' && object.metadata.?labels['app.kubernetes.io/managed-by'].orValue('') == 'trivy-operator'"
