apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: policies
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 1500Mi
    limits.cpu: 8
    limits.memory: 3000Mi
    pods: "10"
