apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: main-grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: main-grafana-credentials
