apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosQuery
metadata:
  name: thanos
  namespace: monitoring
spec:
  replicas: 1
  customStoreLabelSelector:
    matchLabels:
      operator.thanos.io/store-api: "true"
  replicaLabels:
    - prometheus_replica
  logFormat: logfmt
