apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources/gateway-api.git-repository.yaml
  - ../../sources/kyverno.helm-repository.yaml
  - ../../sources/cilium.helm-repository.yaml
  - ../../sources/jetstack.helm-repository.yaml
  - ../../sources/kubelet-csr-approver.helm-repository.yaml
  - ../../sources/external-secrets.helm-repository.yaml
  - ../../sources/fluxcd-community.helm-repository.yaml
  - ../../sources/metrics-server.helm-repository.yaml
  - ../../sources/local-path-provisioner.git-repository.yaml
  - ../../sources/velero.helm-repository.yaml
  - ../../sources/seaweedfs-operator.helm-repository.yaml
  - ../../sources/grafana.helm-repository.yaml
  - ../../sources/grafana-community.helm-repository.yaml
  - ../../sources/prometheus-community.helm-repository.yaml
  - ../../sources/thanos-operator.git-repository.yaml
