apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datastores
resources:
  - cloudnative-pg.helm-release.yaml
  - valkey-operator.helm-release.yaml
  - emqx-operator.helm-release.yaml
