apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: main
  namespace: external-secrets
spec:
  provider:
    webhook:
      # MUST include :80. Provider forces HTTPS
      # For whatever reason, remoteRef.key is URL encoded...
      # Webhook provider is pretty janky
      url: "http://secrets.cloud.test:80/{{ .remoteRef.key | replace \"%2F\" \"/\" }}"
      result:
        jsonPath: "$"
  conditions:
    - namespaces:
        - flux-system
        - cert-manager
        - objects
        - monitoring
