apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: main
  namespace: external-secrets
spec:
  provider:
    webhook:
      url: "http://secrets.cloud.test:80/secrets/{{ .remoteRef.key }}"
      result:
        jsonPath: "$"
