apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: main
  namespace: external-secrets
spec:
  provider:
    webhook: # MUST include :80. Provider forces HTTPS
      url: "http://secrets.cloud.test:80/secrets/{{ .remoteRef.key }}"
      result:
        jsonPath: "$"
  conditions:
    - namespaces:
        - flux
        - cert-manager
        - objects
        - monitoring
