apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - o2-sync.service-account.yaml
  - o2-sync.job.yaml
configMapGenerator:
  - name: o2-sync-script
    files:
      - sync.sh=scripts/sync.sh
  - name: o2-destinations
    files:
      - email.json=destinations/email.json
  - name: o2-dashboards-kubernetes
    files:
      - dashboards/kubernetes-namespace-pod.json
      - dashboards/kubernetes-namespaces.json
      - dashboards/kubernetes-nodes.json
      - dashboards/kubernetes-nodes-pressure.json
  - name: o2-dashboards-openobserve
    files:
      - dashboards/openobserve-infrastructure.json
      - dashboards/openobserve-internals.json
  - name: o2-alerts
    files:
      - alerts/pod_crashloop_backoff.json
      - alerts/pod_oom_killed.json
      - alerts/node_not_ready.json
      - alerts/node_high_disk_usage.json
      - alerts/deployment_replica_mismatch.json
      - alerts/job_failed.json
      - alerts/velero_backup_stale.json
      - alerts/velero_backup_failed.json
      # - alerts/velero_repo_maintenance_failed.json
      - alerts/tetragon_tracingpolicy_load_failed.json
      - alerts/tetragon_enforcement_kill.json
      # - alerts/trivy_critical_image_vulnerabilities.json
      - alerts/cilium_datapath_fast_burn.json
      - alerts/cilium_datapath_slow_burn.json
      - alerts/watchdog.json
      - alerts/high_error_rate.json
      - alerts/flux_helmrelease_failure.json
      - alerts/flux_kustomization_failure.json
      - alerts/flux_source_issue.json
