apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/access
configMapGenerator:
  - name: hubble-auth-proxy-values
    namespace: access
    files:
      - values.yaml=hubble-auth-proxy-values.yaml
    options:
      disableNameSuffixHash: true
  - name: openobserve-auth-proxy-values
    namespace: access
    files:
      - values.yaml=openobserve-auth-proxy-values.yaml
    options:
      disableNameSuffixHash: true
