apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tetragon.helm-release.yaml
  - trivy-operator.helm-release.yaml
configMapGenerator:
  - name: tetragon-values
    namespace: security
    files:
      - values.yaml=tetragon-values.yaml
    options:
      disableNameSuffixHash: true
  - name: trivy-operator-values
    namespace: security
    files:
      - values.yaml=trivy-values.yaml
    options:
      disableNameSuffixHash: true
