apiVersion: rustfs.com/v1alpha1
kind: Tenant
metadata:
  name: main
  namespace: objects
spec:
  credsSecret:
    name: tenant-credentials
  pools:
    - name: primary
      servers: 1
      persistence:
        volumesPerServer: 1
        volumeClaimTemplate:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-path
  policies:
    - name: thanos-readwrite
      document:
        configMapKeyRef:
          name: thanos-policy
          key: policy.json
  users:
    - name: thanos-user
      credsSecret:
        name: thanos-bucket-credentials
      policies:
        - thanos-readwrite
  buckets:
    - name: thanos
