apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-admin
  namespace: objects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-admin
  template:
    metadata:
      labels:
        app: seaweedfs-admin
    spec:
      containers:
        - name: admin
          image: chrislusf/seaweedfs:4.44
          args:
            - admin
            - --master=main-master.objects.svc:9333
            - --port=23646
          ports:
            - containerPort: 23646
