apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-credentials
  namespace: objects
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: objects/tenant-credentials
