apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-policy
  namespace: objects
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:ListBucket", "s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
          "Resource": ["arn:aws:s3:::thanos", "arn:aws:s3:::thanos/*"]
        }
      ]
    }
