apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-bucket-credentials
  namespace: objects
spec:
  refreshPolicy: CreatedOnce
  target:
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: thanos
