apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosRuler
metadata:
  name: main
  namespace: monitoring
spec:
  replicas: 1
  alertmanagerURL: "http://alertmanager-operated.monitoring.svc:9093"
  queryLabelSelector:
    matchLabels:
      app.kubernetes.io/part-of: thanos
      app.kubernetes.io/component: query
  ruleConfigSelector:
    matchLabels:
      operator.thanos.io/rule-file: "true"
  evaluationInterval: 1m
  storage:
    storageClass: local-path
    size: 1Gi
  rulerMode:
    type: Stateful
    stateful:
      objectStorageConfig:
        name: thanos-object-storage
        key: thanos.yaml
