apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
  name: mimir
  namespace: objects
spec:
  seaweedRef:
    name: main
    namespace: objects
  policyRef:
    name: mimir
  subjects:
    - name: mimir
