apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/policies-config
  - allow-hostpath-local-path-provisioner.policy-exception.yaml
  - allow-kyverno-host-network.policy-exception.yaml
  - allow-local-path-helper-pod.policy-exception.yaml
