apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 12h
  releaseName: kubelet-csr-approver
  chart:
    spec:
      chart: kubelet-csr-approver
      version: "1.2.15"
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    providerRegex: ".*"
    providerIpPrefixes:
      - 10.0.0.0/8
    bypassDnsResolution: true
    skipDenyStep: true
    replicas: 1
    leaderElection: false
