apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# every yaml in the dir must be registered here — unregistered files get pruned by flux
resources:
  - cert-manager.helm-release.yaml
  - kubelet-csr-approver.helm-release.yaml
configMapGenerator:
  - name: cert-manager-values
    namespace: certificates
    files:
      - values.yaml=cert-manager-values.yaml
    options:
      disableNameSuffixHash: true
  - name: kubelet-csr-approver-values
    namespace: kube-system
    files:
      - values.yaml=kubelet-csr-approver-values.yaml
    options:
      disableNameSuffixHash: true
