apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: secrets
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 500Mi
    limits.cpu: 1500m
    limits.memory: 750Mi
    pods: "8"
