fullnameOverride: openobserve

image:
  oss:
    repository: public.ecr.aws/zinclabs/openobserve
    tag: v1.0.1

podAnnotations:
  backup.velero.io/backup-volumes-excludes: data

podSecurityContext:
  fsGroup: 2000
  runAsUser: 10000
  runAsGroup: 3000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

cache:
  enabled: true
  mountPath: /var/lib/openobserve-cache
  sizeLimit: 2Gi

persistence:
  enabled: true
  size: 5Gi
  storageClass: local-path
  accessModes:
    - ReadWriteOnce

auth:
  existingRootUserSecret:
    name: openobserve-credentials
    emailKey: ZO_ROOT_USER_EMAIL
    passwordKey: ZO_ROOT_USER_PASSWORD
  ZO_S3_ACCESS_KEY: ""
  ZO_S3_SECRET_KEY: ""

extraEnv:
  - name: ZO_SMTP_ENABLED
    value: "true"
  - name: ZO_SMTP_HOST
    value: "smtp.cloud.test"
  - name: ZO_SMTP_PORT
    value: "25"
  - name: ZO_SMTP_FROM_EMAIL
    value: "alerts@cloud.test"
  - name: ZO_SMTP_ENCRYPTION
    value: ""
  - name: ZO_S3_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: openobserve-s3-credentials
        key: ZO_S3_ACCESS_KEY
  - name: ZO_S3_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: openobserve-s3-credentials
        key: ZO_S3_SECRET_KEY

config:
  ZO_LOCAL_MODE: "true"
  ZO_DATA_CACHE_DIR: "/var/lib/openobserve-cache"
  ZO_LOCAL_MODE_STORAGE: "s3"
  ZO_S3_PROVIDER: "s3"
  ZO_S3_SERVER_URL: "http://s3.cloud.test"
  ZO_S3_REGION_NAME: "local"
  ZO_S3_BUCKET_NAME: "openobserve"
  ZO_TELEMETRY: "false"
  ZO_MMDB_DISABLE_DOWNLOAD: "true"
  ZO_MEM_TABLE_MAX_SIZE: "1024"
  ZO_MAX_FILE_RETENTION_TIME: "600"
  ZO_MAX_FILE_SIZE_IN_MEMORY: "256"
  ZO_MAX_FILE_SIZE_ON_DISK: "256"
  ZO_MEM_DUMP_THREAD_NUM: "2"
  ZO_FILE_MOVE_THREAD_NUM: "2"
  ZO_FILE_MERGE_THREAD_NUM: "2"
  ZO_FILE_PUSH_INTERVAL: "300"
  ZO_COMPACT_ENABLED: "true"
  ZO_COMPACT_DATA_RETENTION_DAYS: "3"
  ZO_COMPACT_INTERVAL: "120"
  ZO_COMPACT_MAX_FILE_SIZE: "1024"
  ZO_MEMORY_CACHE_MAX_SIZE: "1536"
  ZO_MEMORY_CACHE_DATAFUSION_MAX_SIZE: "1536"
  ZO_DISK_CACHE_ENABLED: "true"
  ZO_DISK_CACHE_MAX_SIZE: "1024"
  ZO_LOGS_FILE_RETENTION: "daily"
  ZO_TRACES_FILE_RETENTION: "daily"

resources:
  requests:
    cpu: 500m
    memory: 5Gi
  limits:
    cpu: "4"
    memory: 7Gi

service:
  type: ClusterIP
  http_port: 5080
  grpc_port: 5081

serviceMonitor:
  enabled: false
