apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: access
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: access/oauth2-proxy-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-root-ca
  namespace: access
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: access/platform-root-ca
