apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intermediate-ca
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: intermediate-ca
