apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources/crds/gateway-api.git-repository.yaml
  - ../../sources/cni/cilium.helm-repository.yaml
  - ../../sources/gitops/fluxcd-community.helm-repository.yaml
