installCRDs: true
replicaCount: 1
podSecurityContext:
  runAsNonRoot: true
securityContext:
  runAsGroup: 1000
resources:
  requests:
    cpu: 10m
    memory: 56Mi
  limits:
    cpu: 200m
    memory: 84Mi
certController:
  securityContext:
    runAsGroup: 1000
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 144Mi
webhook:
  securityContext:
    runAsGroup: 1000
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu: 200m
      memory: 60Mi
