apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# every yaml in the dir must be registered here — unregistered files get pruned by flux
resources:
  - seaweedfs-operator.helm-release.yaml
configMapGenerator:
  - name: seaweedfs-operator-values
    namespace: objects
    files:
      - values.yaml=seaweedfs-operator-values.yaml
    options:
      disableNameSuffixHash: true
