apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/00-namespaces
  prune: false
  wait: true
  timeout: 2m
