apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  retryInterval: 5s
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/01-sources
  prune: true
  wait: true
