apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backups-config
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 5s
  dependsOn:
    - name: secrets-config
    - name: objects-config
    - name: backups
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/10-backups-config
  prune: true
  wait: true
  timeout: 10m
