apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backups
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5s
  dependsOn:
    - name: namespaces
    - name: sources
    - name: networking
    # restore drills depend on the local PV types (defaultVolumeType: local)
    - name: storage-config
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/backups
  prune: true
  wait: true
  timeout: 10m
