apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5s
  dependsOn:
    - name: flux
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/flux-config
  prune: false
  force: true
  wait: false
  timeout: 2m
