apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces.yaml
  - 01-sources.yaml
  - 02-crds.yaml
  - 03-cni.yaml
  - 04-networking.yaml
  - 05-secrets.yaml
  - 05-secrets-config.yaml
  - 06-flux.yaml
  - 07-certificates.yaml
  - 07-certificates-config.yaml
  - 08-metrics.yaml
  - 09-storage.yaml
  - 10-objects.yaml
  - 10-objects-config.yaml
  - 11-monitoring.yaml
  - 11-monitoring-config.yaml
