apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources.yaml
  - crds.yaml
  - secrets.yaml
  - secrets-config.yaml
  - certificates.yaml
  - certificates-config.yaml
  - networking.yaml
  - networking-config.yaml
  - flux.yaml
  - flux-config.yaml
  - metrics.yaml
  - policies.yaml
  - policies-config.yaml
  - storage.yaml
  - objects.yaml
  - objects-config.yaml
  - monitoring.yaml
  - monitoring-config.yaml
  - backups.yaml
  - backups-config.yaml
  - logging.yaml
