apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policies-config
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 5s
  dependsOn:
    - name: policies
  sourceRef:
    kind: Bucket
    name: main
  path: ./manifests/local/policies-config
  prune: false
  wait: true
