apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudnative-pg-crds
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/cloudnative-pg/cloudnative-pg
  ref:
    tag: v1.30.0
  ignore: |
    /*
    !/config
    /config/*
    !/config/crd
