apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: thanos-operator
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/thanos-community/thanos-operator
  ref:
    commit: 49cd11f1f3b11fc099f815da4b3dfce243ffeeb3
  ignore: |
    !/bundle.yaml
