apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: index.docker.io/velero/velero-plugin-for-aws:v1.14.2
        volumeMounts:
          - mountPath: /target
            name: plugins
        # resources:
        #   requests:
        #     cpu: ""
        #     memory: ""
        #   limits:
        #     cpu: ""
        #     memory: ""
    credentials: {}
    configuration:
      backupStorageLocation: null
      volumeSnapshotLocation: null
    deployNodeAgent: true
    nodeAgent:
      containerSecurityContext:
        privileged: true
      # resources:
      #   requests:
      #     cpu: ""
      #     memory: ""
      #   limits:
      #     cpu: ""
      #     memory: ""
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
