apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: exec-inventory
spec:
  podSelector:
    matchLabels: {}
  kprobes:
    - call: security_bprm_check
      syscall: false
      args:
        - index: 0
          type: linux_binprm
      message: "exec by pod process (inventory)"
      selectors:
        - matchActions:
            - action: Post
