apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: security
spec:
  hard:
    requests.cpu: 1
    requests.memory: 11Gi
    limits.cpu: 12
    limits.memory: 14Gi
    pods: "20"
