apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# StorageClasses live in ../storage-config (cmdshift/platform#35)
resources:
  - local-path-provisioner.helm-release.yaml
configMapGenerator:
  - name: local-path-provisioner-values
    namespace: storage
    files:
      - values.yaml=local-path-provisioner-values.yaml
    options:
      disableNameSuffixHash: true
