apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: thanos-operator
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/thanos-community/thanos-operator
  ref:
    commit: 15a60a655583acc9bc6d14385ff0b004f4e8e948
  ignore: |
    !/bundle.yaml
