apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server.helm-release.yaml
  - vpa.helm-release.yaml
  - goldilocks.helm-release.yaml
configMapGenerator:
  - name: metrics-server-values
    namespace: kube-system
    files:
      - values.yaml=metrics-server-values.yaml
    options:
      disableNameSuffixHash: true
  - name: vpa-values
    namespace: kube-system
    files:
      - values.yaml=vpa-values.yaml
    options:
      disableNameSuffixHash: true
  - name: goldilocks-values
    namespace: kube-system
    files:
      - values.yaml=goldilocks-values.yaml
    options:
      disableNameSuffixHash: true
