apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-operator.helm-release.yaml
  - kube-prometheus-stack.helm-release.yaml
  - thanos-objstore.external-secret.yaml
  - thanos-operator.kustomization.yaml
configMapGenerator:
  - name: grafana-operator-values
    namespace: monitoring
    files:
      - values.yaml=grafana-operator-values.yaml
    options:
      disableNameSuffixHash: true
  - name: kube-prometheus-stack-values
    namespace: monitoring
    files:
      - values.yaml=kube-prometheus-stack-values.yaml
    options:
      disableNameSuffixHash: true
