apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: thanos-operator
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 5s
  sourceRef:
    kind: GitRepository
    name: thanos-operator
    namespace: flux-system
  path: .
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: thanos-operator-controller-manager
          namespace: thanos-operator-system
        spec:
          template:
            spec:
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
  wait: true
  prune: true
  timeout: 5m
