apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/networking-config
  - local-test.gateway.yaml
  - local-test-redirect.httproute.yaml
  - backups.cilium-network-policy.yaml
  - observability.cilium-network-policy.yaml
  - secrets.cilium-network-policy.yaml
  - security.cilium-network-policy.yaml
