apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: observability
  namespace: observability
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
    - toEntities:
        - kube-apiserver
    - toEntities:
        - cluster
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
            - port: "10257"
              protocol: TCP
            - port: "10259"
              protocol: TCP
    - toFQDNs:
        - matchName: s3.cloud.test
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toFQDNs:
        - matchName: smtp.cloud.test
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
