skipCRDs: true
image:
  tag: "2.3.2"
resources:
  requests:
    cpu: 10m
    memory: 40Mi
  limits:
    cpu: 200m
    memory: 60Mi
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - "ALL"
  seccompProfile:
    type: RuntimeDefault
