apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trivy-operator.helm-release.yaml
configMapGenerator:
  - name: trivy-operator-values
    namespace: scanning
    files:
      - values.yaml=trivy-values.yaml
    options:
      disableNameSuffixHash: true
