apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
  name: mimir
  namespace: objects
spec:
  seaweedRef:
    name: main
    namespace: objects
  statements:
    - effect: Allow
      actions:
        - s3:ListBucket
      resources:
        - mimir
    - effect: Allow
      actions:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      resources:
        - mimir/*
