apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: mimir
  namespace: objects
spec:
  seaweedRef:
    name: main
    namespace: objects
  identityRef:
    name: mimir
  secretRef:
    name: mimir-s3-credentials
