apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-config
  namespace: objects
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: objects/seaweedfs-s3-config
