apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: tempo
  namespace: objects
spec:
  seaweedRef:
    name: main
    namespace: objects
  identityRef:
    name: tempo
  secretRef:
    name: tempo-s3-credentials
