apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bucket-credentials
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: flux-system/bucket-credentials
