apiVersion: v1
kind: Config
clusters:
  - name: local-test
    cluster:
      server: ${local_api_endpoint}
      certificate-authority-data: ${ca_data}
contexts:
  - name: local-test
    context:
      cluster: local-test
      user: oidc
current-context: local-test
users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        command: kubectl
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=${issuer_url}
          - --oidc-client-id=${client_id}
          - --oidc-extra-scope=profile
          - --oidc-extra-scope=email
          - --oidc-pkce-method=S256
          - --listen-address=127.0.0.1:8000
        interactiveMode: IfAvailable
